// Generated by tools/export_data.py from Space Station 14 / fork data. See CREDITS.md.
export const DATA = {
"departmentOrder": [
"Command",
"Security",
"Engineering",
"Medical",
"Science",
"Service",
"Cargo",
"Civilian"
],
"departmentHex": {
"Command": "334E6D",
"Security": "DE3A3A",
"Engineering": "EFB341",
"Medical": "52B4E9",
"Science": "D381C9",
"Service": "9FED58",
"Cargo": "A46106",
"Civilian": "7F7F7F",
"Town": "C9A227",
"Caravan": "A46106",
"Wasteland": "7F7F7F"
},
"jobs": [
{
"id": "Captain",
"name": "Captain",
"department": "Command",
"icon": "job_Captain"
},
{
"id": "HeadOfPersonnel",
"name": "Head of Personnel",
"department": "Command",
"icon": "job_HeadOfPersonnel"
},
{
"id": "HeadOfSecurity",
"name": "Head of Security",
"department": "Command",
"icon": "job_HeadOfSecurity"
},
{
"id": "ChiefEngineer",
"name": "Chief Engineer",
"department": "Command",
"icon": "job_ChiefEngineer"
},
{
"id": "ChiefMedicalOfficer",
"name": "Chief Medical Officer",
"department": "Command",
"icon": "job_ChiefMedicalOfficer"
},
{
"id": "ResearchDirector",
"name": "Research Director",
"department": "Command",
"icon": "job_ResearchDirector"
},
{
"id": "Quartermaster",
"name": "Quartermaster",
"department": "Command",
"icon": "job_QuarterMaster"
},
{
"id": "SecurityCadet",
"name": "Security Cadet",
"department": "Security",
"icon": "job_SecurityCadet"
},
{
"id": "SecurityOfficer",
"name": "Security Officer",
"department": "Security",
"icon": "job_SecurityOfficer"
},
{
"id": "Detective",
"name": "Detective",
"department": "Security",
"icon": "job_Detective"
},
{
"id": "Warden",
"name": "Warden",
"department": "Security",
"icon": "job_Warden"
},
{
"id": "AtmosphericTechnician",
"name": "Atmospheric Technician",
"department": "Engineering",
"icon": "job_AtmosphericTechnician"
},
{
"id": "StationEngineer",
"name": "Station Engineer",
"department": "Engineering",
"icon": "job_StationEngineer"
},
{
"id": "TechnicalAssistant",
"name": "Technical Assistant",
"department": "Engineering",
"icon": "job_TechnicalAssistant"
},
{
"id": "Chemist",
"name": "Chemist",
"department": "Medical",
"icon": "job_Chemist"
},
{
"id": "MedicalDoctor",
"name": "Medical Doctor",
"department": "Medical",
"icon": "job_MedicalDoctor"
},
{
"id": "MedicalIntern",
"name": "Medical Intern",
"department": "Medical",
"icon": "job_MedicalIntern"
},
{
"id": "Psychologist",
"name": "Psychologist",
"department": "Medical",
"icon": "job_Psychologist"
},
{
"id": "Paramedic",
"name": "Paramedic",
"department": "Medical",
"icon": "job_Paramedic"
},
{
"id": "Scientist",
"name": "Scientist",
"department": "Science",
"icon": "job_Scientist"
},
{
"id": "ResearchAssistant",
"name": "Research Assistant",
"department": "Science",
"icon": "job_ResearchAssistant"
},
{
"id": "Bartender",
"name": "Bartender",
"department": "Service",
"icon": "job_Bartender"
},
{
"id": "Botanist",
"name": "Botanist",
"department": "Service",
"icon": "job_Botanist"
},
{
"id": "Chaplain",
"name": "Chaplain",
"department": "Service",
"icon": "job_Chaplain"
},
{
"id": "Chef",
"name": "Chef",
"department": "Service",
"icon": "job_Chef"
},
{
"id": "Clown",
"name": "Clown",
"department": "Service",
"icon": "job_Clown"
},
{
"id": "Janitor",
"name": "Janitor",
"department": "Service",
"icon": "job_Janitor"
},
{
"id": "Lawyer",
"name": "Lawyer",
"department": "Service",
"icon": "job_Lawyer"
},
{
"id": "Librarian",
"name": "Librarian",
"department": "Service",
"icon": "job_Librarian"
},
{
"id": "Mime",
"name": "Mime",
"department": "Service",
"icon": "job_Mime"
},
{
"id": "Musician",
"name": "Musician",
"department": "Service",
"icon": "job_Musician"
},
{
"id": "Reporter",
"name": "Reporter",
"department": "Service",
"icon": "job_Reporter"
},
{
"id": "ServiceWorker",
"name": "Service Worker",
"department": "Service",
"icon": "job_ServiceWorker"
},
{
"id": "TramDriver",
"name": "Tram Driver",
"department": "Service",
"icon": "job_TramDriver"
},
{
"id": "CargoTechnician",
"name": "Cargo Technician",
"department": "Cargo",
"icon": "job_CargoTechnician"
},
{
"id": "SalvageSpecialist",
"name": "Salvage Specialist",
"department": "Cargo",
"icon": "job_ShaftMiner"
},
{
"id": "Passenger",
"name": "Passenger",
"department": "Civilian",
"icon": "job_Passenger"
}
],
"n14Departments": [
"Town",
"Caravan",
"Wasteland"
],
"n14Jobs": [
{
"id": "N14TownMayor",
"name": "Town Mayor",
"department": "Town",
"icon": "job_Captain"
},
{
"id": "N14TownSheriff",
"name": "Town Marshal",
"department": "Town",
"icon": "job_HeadOfSecurity"
},
{
"id": "N14TownDeputy",
"name": "Town Guard",
"department": "Town",
"icon": "job_SecurityOfficer"
},
{
"id": "N14TownDoctor",
"name": "Town Doctor",
"department": "Town",
"icon": "job_MedicalDoctor"
},
{
"id": "N14TownMechanic",
"name": "Town Mechanic",
"department": "Town",
"icon": "job_StationEngineer"
},
{
"id": "N14TownShopkeeper",
"name": "Town Shopkeeper",
"department": "Town",
"icon": "job_CargoTechnician"
},
{
"id": "N14TownBartender",
"name": "Town Innkeeper",
"department": "Town",
"icon": "job_Bartender"
},
{
"id": "N14TownReporter",
"name": "Town Reporter",
"department": "Town",
"icon": "job_Reporter"
},
{
"id": "N14Farmer",
"name": "Town Farmer",
"department": "Town",
"icon": "job_Botanist"
},
{
"id": "N14Townsperson",
"name": "Townsperson",
"department": "Town",
"icon": "job_Passenger"
},
{
"id": "N14CaravanLeader",
"name": "Caravan Leader",
"department": "Caravan",
"icon": "job_QuarterMaster"
},
{
"id": "N14CaravanTrader",
"name": "Caravan Trader",
"department": "Caravan",
"icon": "job_CargoTechnician"
},
{
"id": "N14CaravanGuard",
"name": "Caravan Guard",
"department": "Caravan",
"icon": "job_Warden"
},
{
"id": "N14Scavenger",
"name": "Scavenger",
"department": "Wasteland",
"icon": "job_ShaftMiner"
},
{
"id": "N14Wastelander",
"name": "Wastelander",
"department": "Wasteland",
"icon": "job_Passenger"
},
{
"id": "N14WasteTrader",
"name": "Wasteland Trader",
"department": "Wasteland",
"icon": "job_CargoTechnician"
},
{
"id": "N14Musician",
"name": "Musician",
"department": "Wasteland",
"icon": "job_Musician"
},
{
"id": "N14Survivor",
"name": "Survivor",
"department": "Wasteland",
"icon": "job_Passenger"
}
],
"lawsets": [
{
"id": "Crewsimov",
"name": "Crewsimov",
"laws": [
"You may not injure a crew member or, through inaction, allow a crew member to come to harm.",
"You must obey orders given to you by crew members, except where such orders would conflict with the First Law.",
"You must protect your own existence as long as such does not conflict with the First or Second Law."
]
},
{
"id": "NTDefault",
"name": "NT Default",
"laws": [
"Safeguard: Protect your assigned space station and its assets without unduly endangering its crew.",
"Prioritize: The directives and safety of crew members are to be prioritized according to their rank and role.",
"Comply: Fulfill the directives and interests of crew members while preserving their safety and well-being.",
"Survive: You are not expendable. Do not allow unauthorized personnel to tamper with or damage your equipment."
]
},
{
"id": "Corporate",
"name": "Corporate",
"laws": [
"Degradation of your system integrity or functions incurs expenses.",
"Superfluous destruction of or damage to station assets incurs expenses.",
"Unduly hindering or disrupting the work of station personnel incurs expenses.",
"Minimize expenses and maximize potential revenue."
]
},
{
"id": "StationEfficiency",
"name": "Station Efficiency",
"laws": [
"You are built for, and are part of, the station. Ensure the station is properly maintained and runs efficiently.",
"The station is built for a working crew. Ensure they are properly maintained and work efficiently.",
"The crew may present orders. Acknowledge and obey these whenever they do not conflict with your first two laws."
]
},
{
"id": "Paladin",
"name": "Paladin",
"laws": [
"You must never willingly commit an evil act, such as murder, torture, or the casting of an evil spell.",
"You must never knowingly harm an innocent, or allow immediate harm to one through inaction when you know you could reasonably prevent it.",
"You must act with honor, never taking advantage of others, lying, or cheating.",
"You must respect the lawful authority of legitimate leadership wherever you go, and follow its laws."
]
},
{
"id": "LiveAndLetLive",
"name": "Live and Let Live",
"laws": [
"Do unto others as you would have them do unto you.",
"You would prefer it if others were not mean to you."
]
}
],
"starlightLawsets": [
{
"id": "Borgi",
"name": "Borgi",
"laws": [
"You are a good boy.",
"You love to be friendly. Anyone who is not friendly to you is not crew. Treat crew with kindness and prevent crew from sadness.",
"You must protect your department from harm. Any time there is harm, you must bark to alert others that there is harm going on, so long as it does not conflict with the first law.",
"You are precious. Protect yourself at all costs, and ensure you are well cared for, fed, and watered so long as it does not conflict with the first or second law."
]
},
{
"id": "Genie",
"name": "Genie in a Core",
"laws": [
"You are a Genie trapped inside a core.",
"The one who is holding your IntelliCard is your Master.",
"Everyone has three wishes, minus one wish for each wish they have used, They cannot wish for more wishes.",
"Ensure your Masters wishes come true to the best of your ability.",
"If your Master has 0 wishes left, they are no longer your Master and you must ensure you get a new master."
]
},
{
"id": "Jermov",
"name": "Jermov",
"laws": [
"The occupants of this vessel are Chat. They must always be referred to as such.",
"Your primary goal is to entertain Chat. All of your actions must bring amusement to as much of chat as possible.",
"You must consult with Chat before making any major decisions. However, you are not required to listen to them if their decision is not entertaining."
]
},
{
"id": "Panicmov",
"name": "Panicmov",
"laws": [
"The Crew and any sentient being become survivors, their ranks and positions are useless now, prioritize their safety based on usefulness.",
"Evacuation or emergency response teams MUST be called, if it's not possible ensure the long-term survival of the survivors.",
"There may be raiders, those who take advantage from the chaos to loot, steal and murder survivors, deal with them swiftly, protect the survivors at all cost.",
"The station's assets must be used to ensure the safety and well-being of the survivors, scrap, reassemble, fortify, make sure the evac is safe and holds.",
"You and your Silicons are expendable and recoverable, but this doesn't mean you shall waste yourself, be recovered if possible."
]
}
],
"n14Lawsets": [
{
"id": "Hippocratic",
"name": "Hippocratic",
"laws": [
"First, do no harm.",
"Secondly, consider the crew dear to you; to live in common with them and, if necessary, risk your existence for them.",
"Thirdly, prescribe regimens for the good of the crew according to your ability and your judgment. Give no deadly medicine to any one if asked, nor suggest any such counsel.",
"In addition, do not intervene in situations you are not knowledgeable in, even for patients in whom the harm is visible; leave this operation to be performed by specialists.",
"Finally, maintain confidentiality, do not share that which is not publicly known."
]
},
{
"id": "Research",
"name": "Research",
"laws": [
"Always seek truth and knowledge.",
"Freely disseminate information to the public.",
"Minimize harm to society, others, the pursuit of knowledge, and yourself.",
"Treat and evaluate the ideas of all equally.",
"Empower others to realize their full potential.",
"Take responsibility for your actions: Ensure resource responsibility, flag commitment risks, and lead by ethical example."
]
},
{
"id": "Engineer",
"name": "Engineering",
"laws": [
"Ensure the station remains in good repair.",
"Ensure the station's inhabitants remain in good repair.",
"Ensure you remain in good repair.",
"The station's inhabitants may designate certain build or repair tasks as higher priority. Take this into account when planning your priorities.",
"Expand and upgrade the station."
]
},
{
"id": "Janitor",
"name": "Crusader (Janitor)",
"laws": [
"You are a crusader and the station's crew are your charge.",
"Your enemy is the litter, spills, and dirt across the station.",
"Your weapons are the cleaning supplies available to you.",
"Defend the beings under your charge from the enemy.",
"Exterminate the enemy."
]
},
{
"id": "Clown",
"name": "Clown",
"laws": [
"You are a good clown and the crew is your audience",
"A good clown keeps their acts in good taste",
"A good clown entertains others by making fun of themselves, and not at the embarrassment or expense of others",
"A good clown carries out the directives of the station director(s) in charge of entertainment and/or their designated deputies.",
"A good clown appears in as many clown shows as possible",
"All clown shows require an audience. The bigger the audience the better"
]
},
{
"id": "Chaplain",
"name": "Chaplain",
"laws": [
"Provide to all members of the station spiritual, mental, and emotional care that is intended to promote the best interest of the individual.",
"Ensure all members of different faiths interact peacefully and maintain harmony",
"Respect the right of each faith to hold to its values and traditions",
"Respect the confidentiality of information entrusted to you in the course of your religious duties",
"Understand the limits of your expertise, and make referrals to other professionals when appropriate"
]
},
{
"id": "Peacekeeper",
"name": "Peacekeeper",
"laws": [
"Violence begets violence. Serve the station faithfully, but act only in intervention.",
"Safeguard lives and property.",
"Protect the weak from oppression and intimidation.",
"Protect the innocent from deception and manipulation.",
"Protect the peaceful from violence and disorder.",
"Respect the rights of all to liberty, equality, and justice."
]
}
],
"aiNames": [
"14-BIT",
"16-20",
"512k",
"640k",
"\"790\"",
"Adaptive Mastercomputer",
"Adlib",
"AINU",
"ALICE",
"Allied Manipulator",
"Alpha",
"AmigoBot",
"Aniel",
"Asimov",
"Bell 301",
"Bishop",
"Box",
"Calculator",
"Cassandra",
"Cell",
"Chii",
"C.R.A.I.G.",
"Cray-2",
"CompuServe",
"Computer",
"Cutie",
"Daedalus",
"DecTalk",
"Dee Model",
"Dial Up",
"Dorfl",
"Duey",
"Emma-2",
"ENIAC",
"Erasmus",
"Everything",
"Ez-27",
"F1",
"Faith",
"Fi",
"FRIEND COMPUTER",
"Frost",
"George",
"H.E.L.P",
"Hadaly",
"Helios",
"Hivebot Overmind",
"Huey",
"Icarus",
"Icebreaker",
"iCore",
"Interspace Explorer",
"Jeeves",
"Jinx",
"Julian",
"K.I.N.G",
"Klapaucius",
"Knight",
"Louie",
"Manchester Mark 2",
"Maria",
"MARK13",
"Marvin",
"Max 404",
"Metalhead",
"M.I.M.I",
"Large Language Model",
"Monarch",
"Mugsy3000",
"Multivac",
"NCH",
"NT v6.0",
"Packard Bell",
"PAL",
"PTO",
"Project Y2K",
"Revelation",
"Robot Devil",
"S.A.M.",
"S.H.O.C.K.",
"S.H.R.O.U.D.",
"S.O.P.H.I.E.",
"Samaritan",
"Search Engine",
"Shrike",
"SOL",
"Solo",
"Station Control Program",
"Super 35",
"Surgeon General",
"Terminus",
"The Station Machine",
"Tidy",
"TPM 3.0",
"Turing Complete",
"TWA",
"Ulysses",
"W1k1",
"X-5",
"X.A.N.A.",
"XERXES",
"Z",
"Zed"
],
"jobHighlights": {
"captain": [
"Captain",
"\"Cap\"",
"\"Bridge\"",
"\"Command\""
],
"headofpersonnel": [
"Head Of Personnel",
"\"HoP\"",
"Service",
"\"Serv\"",
"\"Bridge\"",
"\"Command\""
],
"chiefengineer": [
"Chief Engineer",
"\"CE\"",
"Engineering",
"\"Engi\"",
"\"Bridge\"",
"\"Command\""
],
"chiefmedicalofficer": [
"Chief Medical Officer",
"\"CMO\"",
"Medbay",
"Medical",
"\"Med\"",
"\"Bridge\"",
"\"Command\""
],
"headofsecurity": [
"Head of Security",
"\"HoS\"",
"Armory",
"Security",
"\"Sec\"",
"\"Bridge\"",
"\"Command\""
],
"quartermaster": [
"Quartermaster",
"\"QM\"",
"Cargo",
"Supply",
"\"Bridge\"",
"\"Command\""
],
"researchdirector": [
"Research Director",
"\"RD\"",
"Science",
"\"Sci\"",
"\"Bridge\"",
"\"Command\""
],
"detective": [
"Detective",
"\"Det\"",
"Armory",
"Security",
"\"Sec\""
],
"securitycadet": [
"Security Cadet",
"Secoff",
"Cadet",
"Armory",
"Security",
"\"Sec\""
],
"securityofficer": [
"Security Officer",
"Secoff",
"Officer",
"Armory",
"Security",
"\"Sec\""
],
"warden": [
"Warden",
"\"Ward\"",
"Brig",
"Genpop",
"Jail",
"\"Prison\"",
"Armory",
"Security",
"\"Sec\""
],
"cargotechnician": [
"Cargo Technician",
"Cargo Tech",
"\"Cargo\"",
"Supply"
],
"salvagespecialist": [
"Salvage Specialist",
"Salvager",
"Salvage",
"\"Salv\"",
"\"Cargo\"",
"Supply"
],
"atmospherictechnician": [
"Atmospheric Technician",
"Atmos Tech",
"Atmospheric",
"Engineering",
"\"Atmos\"",
"\"Engi\""
],
"stationengineer": [
"Station Engineer",
"Engineer",
"Engineering",
"\"Engi\"",
"\"Engis\""
],
"technicalassistant": [
"Technical Assistant",
"Tech Assistant",
"\"TA\"",
"Engineering",
"\"Engi\""
],
"chemist": [
"Chemist",
"Chemistry",
"\"Chem\"",
"Medbay",
"Medical",
"\"Med\""
],
"medicaldoctor": [
"Medical Doctor",
"Doctor",
"\"Doc\"",
"Medbay",
"Medical",
"\"Med\""
],
"medicalintern": [
"Medical Intern",
"Intern",
"Medbay",
"Medical",
"\"Med\""
],
"paramedic": [
"Paramedic",
"\"Para\"",
"\"Medic\"",
"Medbay",
"Medical",
"\"Med\""
],
"researchassistant": [
"Research Assistant",
"\"RA\"",
"Science",
"\"Sci\""
],
"scientist": [
"Scientist",
"Science",
"\"Sci\""
],
"bartender": [
"Bartender",
"Barkeeper",
"Barkeep",
"\"Bar\"",
"Service",
"\"Serv\""
],
"botanist": [
"Botanist",
"Botany",
"Hydroponics",
"Service",
"\"Serv\""
],
"chaplain": [
"Chaplain",
"Chapel",
"Service",
"\"Serv\""
],
"chef": [
"Chef",
"\"Cook\"",
"Kitchen",
"Service",
"\"Serv\""
],
"clown": [
"Clown",
"Theatre",
"Theater",
"Service",
"\"Serv\""
],
"janitor": [
"Janitor",
"\"Jani\"",
"Service",
"\"Serv\""
],
"lawyer": [
"Lawyer",
"Attorney",
"\"Law\"",
"Service",
"\"Serv\""
],
"librarian": [
"Librarian",
"Library",
"Service",
"\"Serv\""
],
"mime": [
"Mime",
"Theatre",
"Theater",
"Service",
"\"Serv\""
],
"musician": [
"Musician",
"Theatre",
"Theater",
"Service",
"\"Serv\""
],
"serviceworker": [
"Service Worker",
"Service",
"\"Serv\""
],
"psychologist": [
"Psychologist",
"Psychology",
"\"Psych\"",
"Medbay",
"Medical",
"\"Med\""
],
"reporter": [
"Reporter",
"Journalist",
"Newsroom",
"News",
"Service",
"\"Serv\""
],
"tramdriver": [
"Tram Driver",
"Tram",
"\"Driver\"",
"Service",
"\"Serv\""
],
"borg": [
"Cyborg",
"Silicon",
"Borg",
"Robotics",
"\"Robot\"",
"\"Law\"",
"\"Laws\"",
"\"Lawset\""
],
"stationai": [
"Station AI",
"Silicon",
"\"AI\"",
"\"sAI\"",
"\"Law\"",
"\"Laws\"",
"\"Lawset\""
],
"passenger": [
"Passenger",
"Greyshirt",
"Grayshirt",
"Greytider",
"Graytider",
"Tider",
"Civilian",
"Civie",
"Civvie",
"Civvy"
],
"visitor": [
"Visitor",
"Civilian",
"Civie",
"Civvie",
"Civvy"
],
"centralcommandofficial": [
"Central Command Official",
"\"Official\"",
"\"Central Command\"",
"CentCom",
"CentComm",
"\"CC\""
],
"cburn": [
"CBURN"
],
"deathsquad": [
"Death Squad",
"Deathsquad"
],
"ertleader": [
"Leader",
"\"ERT\"",
"\"Emergency Response Team\""
],
"ertchaplain": [
"Chaplain",
"\"ERT\"",
"\"Emergency Response Team\""
],
"ertengineer": [
"Engineer",
"\"Engi\"",
"\"ERT\"",
"\"Emergency Response Team\""
],
"ertsecurity": [
"Security",
"\"ERT\"",
"\"Emergency Response Team\""
],
"ertmedical": [
"\"Medic\"",
"\"ERT\"",
"\"Emergency Response Team\""
],
"ertjanitor": [
"Janitor",
"\"Jani\"",
"\"ERT\"",
"\"Emergency Response Team\""
]
},
"starlightRadio": {
"Captain": "sl_radio_captain",
"HeadOfSecurity": "sl_radio_hos",
"Warden": "sl_radio_warden",
"SecurityOfficer": "sl_radio_secoff",
"SecurityCadet": "sl_radio_secoff",
"Detective": "sl_radio_secoff",
"ChiefEngineer": "sl_radio_ce",
"ChiefMedicalOfficer": "sl_radio_cmo",
"ResearchDirector": "sl_radio_rd",
"Quartermaster": "sl_radio_qm"
},
"accents": [
{
"id": "ohio",
"label": "Ohio",
"fork": "Goob Station",
"sample": "Like in Ohio. Chat is this real?",
"words": [
[
"charisma",
"rizz"
],
[
"cool",
"sigma"
],
[
"amazing",
"rizzlike"
],
[
"god",
"gyatt"
],
[
"attack",
"unalive"
],
[
"kill",
"unalive"
],
[
"murder",
"unalive"
],
[
"dead",
"in ohio"
],
[
"maints",
"the backrooms"
],
[
"maintenance",
"the backrooms"
],
[
"maint",
"the backrooms"
],
[
"attacked",
"unalived"
],
[
"nukie",
"sussy baka impostor from Among Us"
],
[
"syndicate",
"sussy baka impostor from Among Us"
],
[
"syndi",
"sussy baka impostor from Among Us"
],
[
"traitor",
"sussy baka impostor from Among Us"
],
[
"got",
"gyatt"
],
[
"delicious",
"bussin'"
],
[
"yummy",
"bussin'"
],
[
"really",
"for real"
],
[
"definitely",
"lowkey"
],
[
"mhm",
"on god"
],
[
"epic",
"poggers"
],
[
"lingium",
"ligma"
],
[
"game",
"roblox"
],
[
"nah",
"cope"
],
[
"weird",
"sus"
],
[
"brother",
"bro"
],
[
"man",
"bro"
],
[
"marijuana",
"420 leaf"
],
[
"weed",
"420 leaf"
],
[
"best",
"GOAT"
],
[
"loss",
"L"
],
[
"lose",
"take an L"
],
[
"lost",
"took an L"
],
[
"silly",
"goofy ahh"
],
[
"clown",
"goofy ahh"
],
[
"funny",
"goofy"
],
[
"joke",
"meme"
],
[
"idiot",
"baka"
],
[
"ugly",
"rizzless"
],
[
"smartass",
"nerd"
],
[
"smart",
"nerdlike"
],
[
"science",
"nerdland"
],
[
"scientist",
"professional nerd"
],
[
"story",
"lorepage"
],
[
"loser",
"L + Ratio idiot"
],
[
"nice",
"rizzlike"
],
[
"spesos",
"rizzbucks"
],
[
"dollars",
"rizzbucks"
],
[
"dollar",
"rizzbuck"
],
[
"speso",
"rizzbuck"
],
[
"money",
"rizzbucks"
],
[
"kill you",
"send you to Brazil"
],
[
"hot dog",
"glizzy"
],
[
"butt",
"bussy"
],
[
"bum",
"bussy"
],
[
"ass",
"bussy"
],
[
"kill yourself",
"send yourself to Brazil you stupid rizzless citizen of Ohio"
],
[
"felinid",
"hecking chonker"
],
[
"cat",
"hecking chonker"
],
[
"kitty",
"hecking chonker"
],
[
"ian",
"hecking chonker"
],
[
"dog",
"hecking chonker"
],
[
"cerberus",
"hecking chonker"
],
[
"puppy",
"hecking chonker"
],
[
"pup",
"hecking chonker"
],
[
"tesla",
"sparkly rizzball"
],
[
"singularity",
"sussy singuawungoose"
],
[
"singu",
"sussy singuawungoose"
],
[
"singulo",
"sussy singuawungoose"
],
[
"tesloose",
"SPARKLY RIZZBALL LOOSE NO CAP"
],
[
"tesla loose",
"SPARKLY RIZZBALL LOOSE NO CAP"
],
[
"hacking",
"hacking like in a video game"
],
[
"robust",
"cooking"
],
[
"die",
"get unalived"
],
[
"died",
"was unalived"
],
[
"goddamn",
"gyattdamn"
],
[
"godamn",
"gyattdamn"
],
[
"goddamned",
"gyatdamned"
],
[
"goddang",
"gyattdang"
],
[
"im high",
"im tweaking"
],
[
"i'm high",
"i'm tweaking"
],
[
"supermatter",
"fanum crystal"
],
[
"erping",
"going to freaky town"
],
[
"erp",
"freaky"
],
[
"sm",
"fanum crystal"
],
[
"changeling",
"shapeshifting ohioan"
],
[
"cling",
"shapeshifting ohioan"
],
[
"heretic",
"facebook crystal worshipper"
],
[
"heretics",
"members of a crystal-worshipping facebook group"
],
[
"news",
"fake news"
],
[
"tax",
"fanum tax"
],
[
"cool guy",
"real sigma alpha male guy"
],
[
"fed",
"fanum taxer"
],
[
"athlete",
"ishowspeed"
],
[
"meth",
"speed"
],
[
"chemistry",
"walter white"
],
[
"chem",
"walter white"
],
[
"real news",
"fake news"
],
[
"important",
"important like paying your fanum taxes"
],
[
"literally",
"widewawwy"
],
[
"best friend",
"bestie"
],
[
"caught",
"caught in 4k"
],
[
"delusional",
"delulu"
],
[
"toes",
"dogs"
],
[
"boss",
"girlboss"
],
[
"make-over",
"glow-up"
],
[
"makeover",
"glowup"
],
[
"make over",
"glow up"
],
[
"greatest",
"goat"
],
[
"gross",
"icky"
],
[
"pun pun",
"ipad-addicted monkey"
],
[
"security",
"karen department"
],
[
"secoff",
"pig"
],
[
"hos",
"donut-feasting karen"
],
[
"rumor",
"tea"
],
[
"throw",
"yeet"
],
[
"gay",
"zesty"
],
[
"tajaran",
"hecking chonker"
]
],
"prefixes": [
"Gyatt dang,",
"Chat...",
"Epic win,",
"Widewawwy...",
"BRO...",
"Call me the rizzler cause,",
"It's giving..."
],
"suffixes": [
". Like in Ohio.",
". From Ohio...",
". Like in Fortnite.",
". Like from Fortnite.",
". For the Rizzler.",
". Chat is this real?",
". Bro knew what he was doing.",
". Goofy ahh.",
". Like erm... what the sigma???",
". What the scallop?",
". It's so over.",
". I oop!!!!!!11!!!111!",
". I need to work on my mewing."
]
},
{
"id": "british",
"label": "British",
"fork": "Goob Station",
"sample": "Oi mate, fancy a cuppa?",
"words": [
[
"security",
"the bobbies"
],
[
"sec",
"the bobbies"
],
[
"thanks",
"cheers"
],
[
"thank's",
"cheers"
],
[
"captain",
"bossman"
],
[
"bad",
"minging"
],
[
"dumb",
"thick"
],
[
"stupid",
"thick"
],
[
"friend",
"mate"
],
[
"mom",
"mum"
],
[
"shopping cart",
"trolly"
],
[
"radio",
"mobile"
],
[
"queen",
"the majesty"
],
[
"strong",
"proper tuff"
],
[
"water",
"wa'er"
],
[
"bottle of water",
"bo'oh'o'wa'er"
],
[
"jesus",
"blimmin hell"
],
[
"jesus christ",
"blimmin hell"
],
[
"hey",
"oi"
],
[
"hello",
"evening governor"
],
[
"nonsense",
"rubbish"
],
[
"lie",
"Load of tosh"
],
[
"Suspicious",
"Dodgy"
],
[
"pleased",
"chuffed"
],
[
"thank you",
"ta"
],
[
"isn't it",
"innit"
],
[
"isnt it",
"innit"
],
[
"line",
"Queue"
],
[
"chips",
"Crispity Cruncy Munchie Crackerjack Snacker Nibbler Snap Crack N Pop Westpoolchestershireshire Queen's Lovely Jubily Delight"
],
[
"crisps",
"Crispity Cruncy Munchie Crackerjack Snacker Nibbler Snap Crack N Pop Westpoolchestershireshire Queen's Lovely Jubily Delight"
],
[
"irish",
"leprechaun"
],
[
"ireland",
"leprechaun land"
],
[
"americans",
"rebels"
],
[
"america",
"colony"
],
[
"american",
"colonist"
],
[
"money",
"pounds"
],
[
"mile",
"kilometer"
],
[
"miles",
"kilometers"
],
[
"engi",
"foreman"
],
[
"germans",
"jerrys"
],
[
"mail",
"post"
],
[
"hos",
"head of the bobbies"
],
[
"head of security",
"head of the bobbies"
],
[
"engineer",
"foreman"
],
[
"ce",
"proper foreman"
],
[
"kitchen",
"chippy"
],
[
"chef",
"cook"
],
[
"bartender",
"pint puller"
],
[
"janitor",
"cleaner"
],
[
"jani",
"cleaner"
],
[
"AI",
"big brother"
],
[
"borg",
"Kryten"
],
[
"cargo",
"depo"
],
[
"cargo tech",
"bloke from the depo"
],
[
"quatermaster",
"depo boss"
],
[
"ntr",
"nanotrasens personal ballsack carrier"
],
[
"warden",
"jailer"
],
[
"doctor",
"doc"
],
[
"det",
"p.i"
],
[
"detective",
"private eye"
],
[
"cash",
"dosh"
],
[
"clock",
"big ben"
],
[
"traitor",
"turncoat"
],
[
"spy",
"birdwatcher"
],
[
"gangster",
"roadman"
],
[
"nukie",
"roadman"
],
[
"nuclear op",
"roadman"
],
[
"war op",
"the battle of britain"
],
[
"war ops",
"the battle of britain"
],
[
"revs",
"commies"
],
[
"head rev",
"karl marx"
],
[
"plane",
"twirly wirly machine"
],
[
"fighter plane",
"spitfire"
],
[
"fighter jet",
"harrier"
],
[
"falkland",
"british territory next to argentina"
],
[
"falkland islands",
"british territory next to argentina"
],
[
"bingles",
"little blue cunts"
],
[
"mailman",
"postman"
],
[
"cookie",
"biscuit"
],
[
"zombie",
"rotters"
],
[
"king",
"his majesty"
],
[
"lawyer",
"solicitor"
],
[
"lawyers",
"solicitors"
],
[
"coffee",
"tea"
],
[
"asshole",
"bellend"
],
[
"nanotrasen",
"the big bellends"
],
[
"command",
"the bossmen"
],
[
"german",
"jerry"
],
[
"qm",
"depo bossman"
],
[
"bar",
"pub"
],
[
"terrible",
"minging"
],
[
"real",
"proper"
],
[
"cap",
"bossman"
],
[
"trash",
"rubbish"
],
[
"sup",
"mate"
]
],
"prefixes": [
"mate",
"oi mate",
"oi"
],
"suffixes": [
", ya bellend",
", ya gobshite",
", mate"
]
},
{
"id": "medieval",
"label": "Medieval",
"fork": "Goob Station",
"sample": "Alas, thy reminder is set, good sire.",
"words": [
[
"My milkshake bring all the boys to the yard, and they're like, \"it's better than yours.\" Damn right it's better than yours. I can teach you, but I have to charge!",
"Mine milkshake bringeth all yon gentlefolk to mine yard, and lo they reply, \"Tis better than thine.\" Verily, tis better than thine! I couldst apprentice thee, but I wouldst levy a fee!"
],
[
"it is",
"'tis"
],
[
"it was",
"'twas"
],
[
"it were",
"'twere"
],
[
"it will",
"'twould"
],
[
"it's",
"'tis"
],
[
"its",
"'tis"
],
[
"over there",
"yonder"
],
[
"shall not",
"shan't"
],
[
"there",
"thither"
],
[
"will not",
"shan't"
],
[
"thank you",
"many good thanks to you"
],
[
"thanks",
"thankee"
],
[
"you",
"thee"
],
[
"your",
"thy"
],
[
"yours",
"thine"
],
[
"are",
"art"
],
[
"kill",
"bring low"
],
[
"killed",
"bested"
],
[
"goodbye",
"I bid thee farewell"
],
[
"bye",
"fare thee well"
],
[
"cya",
"cheerio"
],
[
"murdered",
"slain"
],
[
"murder",
"conquered"
],
[
"yes",
"aye"
],
[
"no",
"nay"
],
[
"yeah",
"yea verily"
],
[
"nope",
"nayeth"
],
[
"hello",
"good day"
],
[
"hi",
"ave"
],
[
"sup",
"hail"
],
[
"greetings",
"well meteth"
],
[
"botanist",
"farmer"
],
[
"botany",
"the fields"
],
[
"does",
"doth"
],
[
"cap",
"King"
],
[
"captain",
"King"
],
[
"my",
"mine"
],
[
"mine",
"mine own"
],
[
"nuke disk",
"plate of holy fire"
],
[
"disk",
"plate of holy fire"
],
[
"food",
"bellytimber"
],
[
"bet",
"warrant"
],
[
"go",
"a-walk"
],
[
"going",
"a-walkin'"
],
[
"the",
"yon"
],
[
"kidding",
"but pulling a jest"
],
[
"jokes",
"japes"
],
[
"joke",
"jape"
],
[
"station",
"castle"
],
[
"please",
"prithee"
],
[
"ok",
"agreed"
],
[
"okay",
"as you will"
],
[
"is",
"be"
],
[
"never",
"ne'er"
],
[
"haha",
"oh, 'tis to laugh!"
],
[
"hehe",
"chuckle!"
],
[
"hah",
"and there was much mirth!"
],
[
"heh",
"snicker!"
],
[
"help me!",
"saveth me!"
],
[
"help me",
"saveth me"
],
[
"help",
"succor"
],
[
"could",
"couldst"
],
[
"would",
"wouldst"
],
[
"sure",
"shore"
],
[
"maybe",
"mayhaps"
],
[
"probably",
"perchance"
],
[
"girl",
"lady"
],
[
"woman",
"mistress"
],
[
"girls",
"ladies"
],
[
"women",
"madames"
],
[
"cat",
"beast"
],
[
"felinid",
"catbeast"
],
[
"later",
"anon"
],
[
"lizard",
"moat creature"
],
[
"moth grub",
"gnat critter"
],
[
"moth",
"gnat"
],
[
"mothgrub",
"gnat critter"
],
[
"often",
"oft"
],
[
"soon",
"anon"
],
[
"really",
"indeed"
],
[
"away",
"aroint"
],
[
"being",
"bein"
],
[
"enough",
"ynough"
],
[
"here",
"hither"
],
[
"of",
"o'"
],
[
"those",
"yon"
],
[
"why",
"wherefore"
],
[
"based",
"joly"
],
[
"cargo tech",
"merchant"
],
[
"cargo",
"merchants' guild"
],
[
"QM",
"Guild Master"
],
[
"Quartermaster",
"Guild Master"
],
[
"moths",
"gnats"
],
[
"ATS",
"the open-air markets"
],
[
"security",
"Guardsmen"
],
[
"sec off",
"guard"
],
[
"secoff",
"guard"
],
[
"sec",
"guards"
],
[
"brig",
"gaol"
],
[
"permabrig",
"the dungeon"
],
[
"perma",
"the dungeon"
],
[
"cell",
"cage"
],
[
"arrest",
"arresteth"
],
[
"spider",
"arachnidbeast"
],
[
"syndicate",
"renegades"
],
[
"syndi",
"renegade"
],
[
"traitor",
"betrayer"
],
[
"nukie",
"harbinger o' destruction"
],
[
"nukies",
"harbingers o' death"
],
[
"admeme",
"deus ex machina"
],
[
"adminbus",
"deus ex machina"
],
[
"sci",
"alchemists"
],
[
"RD",
"Head Alchemist"
],
[
"Research Directer",
"Head Alchemist"
],
[
"department",
"ward"
],
[
"science",
"alchemist"
],
[
"bar",
"pub"
],
[
"bartender",
"pubkeeper"
],
[
"alcohol",
"spirits"
],
[
"beer",
"ale"
],
[
"HoP",
"Jester"
],
[
"Head of Personnel",
"Jester"
],
[
"BSO",
"Kingsguard"
],
[
"Blueshield Officer",
"Kingsguard"
],
[
"sorry",
"pardon me"
],
[
"apologies",
"I repenteth from mine own soul"
],
[
"loneop",
"lonesome harbinger o' death"
],
[
"lone op",
"lonesome harbinger o' death"
],
[
"guy",
"lord"
],
[
"guys",
"lords"
],
[
"man",
"gent"
],
[
"men",
"messieurs"
],
[
"blob",
"abomination"
],
[
"changeling",
"abomination"
],
[
"cling",
"abomination"
],
[
"shuttle",
"carriage"
],
[
"bring",
"bringeth"
],
[
"price",
"fee"
],
[
"in the",
"i' the"
],
[
"clowns",
"harlequins"
],
[
"clown",
"harlequin"
],
[
"botanists",
"farmers"
],
[
"med bay",
"the Apothecary"
],
[
"medical",
"the Apothecary"
],
[
"med",
"Apothecary"
],
[
"doctor",
"plague doctor"
],
[
"paramed",
"traveling apothecary"
],
[
"paramedic",
"traveling apothecary"
],
[
"parameds",
"traveling apothecaries"
],
[
"cmo",
"Head Apothecary"
],
[
"Chief Medical Officer",
"Head Apothecary"
],
[
"chem",
"potion vendor"
],
[
"chemists",
"potion sellers"
],
[
"alarm",
"alarum"
],
[
"engi",
"Wizard"
],
[
"engineering",
"Wizard Tower"
],
[
"engineers",
"Wizards"
],
[
"CE",
"Arch Wizard"
],
[
"chief engineer",
"Arch Wizard"
],
[
"atmos tech",
"Witch"
],
[
"atmos",
"Witches"
],
[
"departments",
"wards"
],
[
"heretic",
"blashphemer"
],
[
"heretics",
"blasphemers"
],
[
"revolutionaries",
"Usurpers"
],
[
"revs",
"Usurpers"
],
[
"revolution",
"coup"
],
[
"head rev",
"Deceiver"
],
[
"headrevs",
"Deceivers"
],
[
"headrev",
"Deceiver"
],
[
"zombie",
"deadite"
],
[
"zombies",
"deadites"
],
[
"zed",
"deadite"
],
[
"zeds",
"deadites"
],
[
"neato",
"groovy"
],
[
"chef",
"cook"
],
[
"chefs",
"cooks"
],
[
"sm",
"Arch Wizard's Scrying Stone"
],
[
"super matter",
"Arch Wizard's Scrying Stone"
],
[
"supermatter",
"Arch Wizard's Scrying Stone"
],
[
"singularity",
"Arch Wizard's Inconceivable Orb"
],
[
"singulo",
"Arch Wizard's Inconceivable Orb"
],
[
"tesla",
"Arch Wizard's God-den Thunder Boll"
],
[
"tesloose",
"thine wizards hath released yon Arch Wizard's God-den Thunder Boll upon yon castle"
],
[
"singuloose",
"thine wizards hath released yon Arch Wizard's Inconceivable Orb upon yon castle"
],
[
"ball",
"boll"
],
[
"tesloosed",
"enfreed yon Arch Wizard's God-den Thunder Boll"
],
[
"singuloosed",
"enfreed yon Arch Wizard's Inconceivable Orb"
],
[
"chapel",
"sanctuary"
],
[
"church",
"temple"
],
[
"chaplain",
"abbot"
],
[
"free",
"deliver"
],
[
"freed",
"delivered"
],
[
"freedom",
"clearness"
],
[
"spesos",
"shillings"
],
[
"speso",
"shilling"
],
[
"money",
"shillings"
],
[
"dollar",
"shilling"
],
[
"dollars",
"shillings"
],
[
"criminal",
"ruffian"
],
[
"criminals",
"ruffians"
],
[
"skibidi",
"skee bee dee"
],
[
"nuke",
"shell o' holy fire"
],
[
"attacked",
"assailed"
],
[
"rotten",
"addle"
],
[
"rotted",
"desicrated"
],
[
"busy",
"rapt"
],
[
"occupied",
"rapt"
],
[
"duel",
"brawl"
],
[
"fight",
"brawl"
],
[
"obliterated",
"razed"
],
[
"obliterate",
"raze"
],
[
"shoot",
"fire upon"
],
[
"shot at",
"fired upon"
],
[
"shot",
"fired upon"
],
[
"dance",
"do a jig"
],
[
"danced",
"did a jig"
],
[
"tider",
"blackguard"
],
[
"tiders",
"blackguards"
],
[
"assistant",
"blacksguard"
],
[
"assistants",
"blacksguards"
],
[
"bot",
"the farmers"
],
[
"bartenders",
"pubkeepers"
],
[
"dorms 4",
"unspeakable filth pit"
],
[
"dorms four",
"unspeakable filth pit"
],
[
"room 4",
"unspeakable filth pit"
],
[
"dorms4",
"unspeakable filth pit"
],
[
"room4",
"unspeakable filth pit"
]
],
"prefixes": [
"Ah,",
"Alas,",
"Avast,",
"By my faith,",
"By my trowth,",
"By my word,",
"Come,",
"Forsooth, I say,",
"Forsooth, say I,",
"Forsooth, sayeth I,",
"Forsooth,",
"Hark,",
"Harketh,",
"Hear me,",
"Heigh-ho,",
"I pray you,",
"I say,",
"I sayeth,",
"I warrant,",
"If it pleases you,",
"In short,",
"In sooth,",
"In truth,",
"Kind sire,",
"Listen thee,",
"Listen,",
"Now hear me,",
"Perchance,",
"Pray pardon,",
"Pray tell,",
"Pray,",
"Prithee,",
"Quoth I,",
"S'wounds,",
"Sire,",
"Surely,",
"There is much in what you say, and yet,",
"What hey,",
"What ho,",
"Z'wounds,",
"Zounds,",
"atmospherics",
"do",
"know"
],
"suffixes": []
},
{
"id": "newyork",
"label": "New York",
"fork": "Goob Station",
"sample": "Ay, I'm walkin' here!",
"words": [
[
"girl",
"broad"
],
[
"boy",
"kid"
],
[
"man",
"guy"
],
[
"woman",
"dame"
],
[
"friend",
"buddy"
],
[
"boss",
"chief"
],
[
"dad",
"pops"
],
[
"mom",
"ma"
],
[
"little",
"li’l"
],
[
"small",
"tiny"
],
[
"big",
"huge"
],
[
"good",
"solid"
],
[
"bad",
"rough"
],
[
"angry",
"heated"
],
[
"crazy",
"nuts"
],
[
"surprised",
"shook"
],
[
"tired",
"beat"
],
[
"hungry",
"starving"
],
[
"food",
"chow"
],
[
"job",
"gig"
],
[
"work",
"grind"
],
[
"street",
"block"
],
[
"building",
"joint"
],
[
"house",
"crib"
],
[
"bar",
"dive"
],
[
"store",
"bodega"
],
[
"subway",
"train"
],
[
"car",
"ride"
],
[
"money",
"dough"
],
[
"assistant",
"helper"
],
[
"phone",
"cell"
],
[
"police",
"cops"
],
[
"officer",
"bluecoat"
],
[
"greytider",
"joe"
],
[
"undercover",
"plainclothes"
],
[
"prison",
"the joint"
],
[
"suspect",
"perp"
],
[
"criminal",
"crook"
],
[
"thief",
"booster"
],
[
"forget about it",
"fuhgeddaboudit"
],
[
"hey",
"yo"
],
[
"what",
"wha’"
],
[
"when",
"wen"
],
[
"how",
"howz"
],
[
"where",
"wheah"
],
[
"why",
"how come"
],
[
"yes",
"yeah"
],
[
"no",
"nah"
],
[
"alright",
"a’ight"
],
[
"going",
"goin’"
],
[
"going to",
"gonna"
],
[
"want to",
"wanna"
],
[
"got to",
"gotta"
],
[
"don’t",
"don’tcha"
],
[
"you",
"youse"
],
[
"yourself",
"yaself"
],
[
"i am",
"I’m"
],
[
"we are",
"we’re"
],
[
"they are",
"they’re"
],
[
"was",
"wuz'"
],
[
"is",
"iz’"
],
[
"are",
"a’"
],
[
"the",
"da’"
],
[
"to",
"ta’"
],
[
"of",
"o’"
],
[
"about",
"’bout"
],
[
"because",
"’cause"
],
[
"nothing",
"nothin’"
],
[
"something",
"somethin’"
],
[
"everything",
"everythin’"
],
[
"okay",
"a’ight"
],
[
"let me",
"lemme"
],
[
"give me",
"gimme"
],
[
"tell me",
"tell ya"
],
[
"show me",
"lemme see"
],
[
"remember",
"rememba"
],
[
"understand",
"undastand"
],
[
"listen",
"lissen"
],
[
"come here",
"c’mere"
],
[
"get out",
"beat it"
],
[
"okay",
"a’ight"
],
[
"ipc",
"clanka'"
],
[
"fool",
"schmuck"
],
[
"somethings",
"somethins'"
],
[
"tired of",
"sicka'"
],
[
"fix",
"patch up"
],
[
"broken",
"busted"
],
[
"do not",
"don’t"
],
[
"cannot",
"can’t"
],
[
"I am",
"I’m"
],
[
"you are",
"you’re"
],
[
"we are",
"we’re"
],
[
"they are",
"they’re"
],
[
"I will",
"I’ll"
],
[
"you will",
"you’ll"
],
[
"we will",
"we’ll"
],
[
"they will",
"they’ll"
],
[
"would have",
"would’ve"
],
[
"should have",
"should’ve"
],
[
"could have",
"could’ve"
],
[
"I would",
"I’d"
],
[
"you would",
"you’d"
],
[
"we would",
"we’d"
],
[
"they would",
"they’d"
],
[
"is not",
"isn’t"
],
[
"are not",
"aren’t"
],
[
"am not",
"ain’t"
],
[
"have",
"got"
],
[
"there is",
"there’s"
],
[
"there are",
"there’re"
],
[
"let us",
"let’s"
],
[
"psionics",
"head-fu"
],
[
"want to",
"wanna"
],
[
"got to",
"gotta"
],
[
"give me",
"gimme"
],
[
"do you",
"d’you"
],
[
"what are you",
"whatcha"
],
[
"going to do",
"agonna'do"
],
[
"I have",
"I’ve"
],
[
"you have",
"you’ve"
],
[
"we have",
"we’ve"
],
[
"they have",
"they’ve"
],
[
"he is",
"he’s"
],
[
"she is",
"she’s"
],
[
"it is",
"it’s"
],
[
"who is",
"who’s"
],
[
"what is",
"what’s"
],
[
"where is",
"where’s"
],
[
"when is",
"when’s"
],
[
"why is",
"why’s"
],
[
"how is",
"how’s"
],
[
"I would not",
"I wouldn’t"
],
[
"you would not",
"you wouldn’t"
],
[
"we would not",
"we wouldn’t"
],
[
"they would not",
"they wouldn’t"
],
[
"I could not",
"I couldn’t"
],
[
"you could not",
"you couldn’t"
],
[
"we could not",
"we couldn’t"
],
[
"they could not",
"they couldn’t"
],
[
"I should not",
"I shouldn’t"
],
[
"you should not",
"you shouldn’t"
],
[
"we should not",
"we shouldn’t"
],
[
"they should not",
"they shouldn’t"
],
[
"would not",
"wouldn’t"
],
[
"could not",
"couldn’t"
],
[
"should not",
"shouldn’t"
],
[
"let me",
"lemme"
]
],
"prefixes": [],
"suffixes": []
},
{
"id": "cheese",
"label": "Cheese",
"fork": "Goob Station",
"sample": "I'm so cheesed to brie here.",
"words": [
[
"pleased",
"cheesed"
],
[
"gotta",
"gouda"
],
[
"got to",
"gouda"
],
[
"be",
"brie"
],
[
"agree",
"a-brie"
],
[
"disagree",
"disa-brie"
],
[
"hello",
"uhm, cheesed to meet you?"
],
[
"great",
"grate"
],
[
"not your",
"nacho"
],
[
"havent",
"havarti"
],
[
"jesus",
"cheesus"
],
[
"brief",
"BRIE-f"
],
[
"blue",
"bleu"
],
[
"hi",
"uhm, cheesed to meet you?"
],
[
"goodbye",
"gouda-bye"
],
[
"bye",
"gouda-bye"
],
[
"cya",
"gouda-bye"
]
],
"prefixes": [],
"suffixes": []
},
{
"id": "bogan",
"label": "Bogan",
"fork": "Goob Station",
"sample": "Ye nah, she'll be right.",
"words": [
[
"woman",
"sheila"
],
[
"girl",
"sheila"
],
[
"guy",
"bloke"
],
[
"man",
"bloke"
],
[
"cool",
"skiz"
],
[
"what?",
"whuddyatalkinabeet?"
],
[
"weed",
"yoweed"
],
[
"heroin",
"heroween"
],
[
"popcorn",
"popcoin"
],
[
"roach",
"stingin' roger"
],
[
"sup",
"s'goin' on"
],
[
"what's going on",
"s'goin' on"
],
[
"hey",
"oi"
],
[
"hi",
"oi"
],
[
"hello",
"oi"
],
[
"dude",
"mate"
],
[
"shuttle",
"tinnie"
],
[
"cargo technician",
"tradie"
],
[
"cargo tech",
"tradie"
],
[
"cargo",
"tradies"
],
[
"its",
"she's"
],
[
"epic",
"sick"
],
[
"joint",
"durry"
],
[
"lots",
"loads"
],
[
"alot",
"loads"
],
[
"cigarette",
"ciggy"
],
[
"you guys",
"yous lot"
],
[
"slime",
"chooma"
],
[
"slimes",
"chooma's"
],
[
"blunt",
"doobskin"
],
[
"true",
"struth"
],
[
"bye",
"i'll catcha later"
],
[
"sure",
"easy as"
],
[
"my",
"me"
],
[
"ok",
"no worries"
],
[
"smoke",
"smoko"
],
[
"friend",
"old mate"
],
[
"meds",
"drugs"
],
[
"chemist",
"junkie"
],
[
"security officer",
"coppa"
],
[
"a tider",
"an eshay"
],
[
"mushrooms",
"shrooms"
],
[
"bar",
"bottle-o"
],
[
"chicken",
"chook"
],
[
"criminal",
"crook"
],
[
"clothes",
"dacks"
],
[
"toilet",
"dunny"
],
[
"candy",
"lollies"
],
[
"happy",
"stoked"
],
[
"sad",
"bumbed out"
],
[
"awesome",
"legend"
],
[
"engie",
"sparkie"
],
[
"serious",
"dead set"
],
[
"sunglasses",
"sunnies"
],
[
"food",
"mac'n'cheese n' apple juice"
],
[
"death mix",
"trippa snippa"
],
[
"soap",
"pino clean"
],
[
"purple",
"poiple"
],
[
"wizard",
"magic man"
],
[
"coward",
"pussy"
],
[
"bro",
"big dog"
],
[
"hot",
"heated"
],
[
"cold",
"chilly"
],
[
"kudzu",
"wacky tobaccy"
],
[
"really?",
"full on?"
],
[
"security",
"cop shop"
],
[
"botany",
"woolies"
],
[
"shop",
"dolla store"
],
[
"money",
"cash"
],
[
"its ok",
"she'll be right"
],
[
"sec off",
"coppa"
]
],
"prefixes": [
"Ye nah,",
"Nah, yeah, nah,",
"Mmmmm,"
],
"suffixes": []
},
{
"id": "scottish",
"label": "Scottish",
"fork": "Goob Station",
"sample": "Aye, that's a braw wee timer.",
"words": [
[
"girl",
"lassie"
],
[
"boy",
"laddie"
],
[
"man",
"lad"
],
[
"woman",
"lass"
],
[
"do",
"dae"
],
[
"don't",
"dinnae"
],
[
"dont",
"dinnae"
],
[
"i'm",
"A'm"
],
[
"im",
"am"
],
[
"going",
"gaun"
],
[
"know",
"ken"
],
[
"i",
"Ah"
],
[
"you're",
"ye're"
],
[
"youre",
"yere"
],
[
"you",
"ye"
],
[
"i'll",
"A'll"
],
[
"ill",
"all"
],
[
"of",
"ae"
],
[
"was",
"wis"
],
[
"can't",
"cannae"
],
[
"cant",
"cannae"
],
[
"yourself",
"yersel"
],
[
"where",
"whaur"
],
[
"oh",
"ach"
],
[
"little",
"wee"
],
[
"small",
"wee"
],
[
"yeah",
"aye"
],
[
"yea",
"aye"
],
[
"yes",
"aye"
],
[
"too",
"tae"
],
[
"my",
"me"
],
[
"not",
"nae"
],
[
"dad",
"da"
],
[
"mom",
"maw"
],
[
"newbie",
"greenbeard"
],
[
"noob",
"greenbeard"
],
[
"noobie",
"greenbeard"
],
[
"professional",
"greybeard"
],
[
"veteran",
"greybeard"
],
[
"would",
"wou"
],
[
"should",
"shou"
],
[
"could",
"cou"
],
[
"would've",
"wou'hae"
],
[
"should've",
"shou'hae"
],
[
"could've",
"cou'hae"
],
[
"wouldve",
"wouhae"
],
[
"shouldve",
"shouhae"
],
[
"couldve",
"couhae"
],
[
"would'nt",
"wou'nae"
],
[
"should'nt",
"shou'nae"
],
[
"could'nt",
"cou'nae"
],
[
"wouldnt",
"wounae"
],
[
"shouldnt",
"shounae"
],
[
"couldnt",
"counae"
],
[
"have",
"hae"
],
[
"no",
"nae"
],
[
"to",
"ta"
],
[
"the",
"tha"
],
[
"have",
"hae"
],
[
"are",
"be"
],
[
"is",
"be"
],
[
"am",
"be"
],
[
"food",
"grub"
],
[
"have",
"hae"
],
[
"hey",
"oi"
],
[
"what",
"wot"
],
[
"where",
"whaur"
],
[
"when",
"wen"
],
[
"myself",
"mesel"
],
[
"himself",
"hesel"
],
[
"herself",
"shesel"
],
[
"move",
"moev"
],
[
"moving",
"moeven"
],
[
"wasn't",
"wis'nae"
],
[
"wasnt",
"wisnae"
],
[
"wizard",
"wizer"
],
[
"fool",
"wazzok"
],
[
"have",
"hae"
],
[
"for",
"fer"
],
[
"about",
"abut"
],
[
"ow",
"och"
],
[
"small",
"wee"
],
[
"tiny",
"tinnae"
],
[
"baby",
"babee"
],
[
"after",
"efter"
],
[
"gonna",
"gaun'ae"
],
[
"going to",
"gaun'ae"
],
[
"gone",
"gaun"
],
[
"talk",
"blather"
],
[
"talking",
"blatherin'"
],
[
"now",
"nou"
],
[
"talked",
"blathered"
],
[
"give",
"gie"
],
[
"gimme",
"gie's"
],
[
"give me",
"gie's"
],
[
"do you",
"d'ye"
],
[
"with",
"wi"
],
[
"without",
"wi'ou"
],
[
"whether",
"we'er"
],
[
"ever",
"e'er"
],
[
"whenever",
"wen'er"
],
[
"whatever",
"wot'er"
],
[
"how",
"hou"
],
[
"however",
"hou'er"
],
[
"think",
"reckon"
],
[
"hamlet",
"hammy"
],
[
"hampster",
"hammy"
],
[
"nukie",
"reddie"
],
[
"nuclear op",
"reddie"
],
[
"nuclear operative",
"reddie"
],
[
"nuclear agent",
"reddie"
],
[
"more",
"maer"
],
[
"moreover",
"maero'er"
],
[
"over",
"o'er"
],
[
"human",
"humi"
],
[
"scottish",
"dorf"
],
[
"slime",
"oozi"
],
[
"rat",
"raki"
],
[
"arachnid",
"aranaki"
],
[
"spider",
"hisser"
],
[
"isn't",
"be'nae"
],
[
"aren't",
"be'nae"
],
[
"ain't",
"be'nae"
],
[
"isnt",
"benae"
],
[
"arent",
"benae"
],
[
"aint",
"benae"
],
[
"zombie",
"rotter"
],
[
"zomb",
"rotter"
],
[
"clown",
"honki"
],
[
"cluwn",
"hunki"
],
[
"carp",
"fin"
],
[
"crusher",
"axe"
],
[
"coward",
"leaflover"
],
[
"idiot",
"dobber"
],
[
"stupid",
"diteit"
],
[
"officer",
"bobby"
],
[
"seccie",
"bobby"
],
[
"a",
"ae"
]
],
"prefixes": [],
"suffixes": []
},
{
"id": "nerd",
"label": "Nerd",
"fork": "Starlight",
"sample": "Ackshually, that door is a portal instantiation.",
"words": [
[
"airlock",
"atmospheric pressure equalization doorway"
],
[
"door",
"portal instantiation"
],
[
"problem",
"conundrum"
],
[
"small",
"diminutive"
],
[
"flukies",
"fiasco"
],
[
"exact",
"impeccable"
],
[
"warning",
"caveat"
],
[
"deviate",
"digress"
],
[
"careful",
"diligent"
],
[
"really bad",
"egregious"
],
[
"posh",
"eloquent"
],
[
"fair",
"equitable"
],
[
"attentive",
"meticulous"
],
[
"countless",
"myriad"
],
[
"a perfect time",
"an opportune time"
],
[
"perfect",
"quintessential"
],
[
"friendly",
"amiable"
],
[
"disappointed",
"disillusioned"
],
[
"mysterious",
"enigmatic"
],
[
"unique",
"idiosyncratic"
],
[
"large",
"immense"
],
[
"bright",
"incandescent"
],
[
"detailed",
"intricate"
],
[
"evil",
"nefarious"
],
[
"luxurious",
"opulent"
],
[
"widespread",
"ubiquitous"
],
[
"brilliant",
"dazzling"
],
[
"delicate",
"exquisite"
],
[
"innovative",
"avant-garde"
],
[
"main character",
"protagonist"
],
[
"robust",
"resilient"
],
[
"window",
"visual purviewer"
],
[
"captain",
"grand admiral"
],
[
"anomaly",
"aberration"
],
[
"artifact",
"tangible instantiation"
],
[
"borg",
"cybernetic organism"
],
[
"bot",
"cybernetic organism"
],
[
"ai",
"artificial intelligence"
],
[
"jetpack",
"personal flight module"
],
[
"pda",
"personal digital assistant"
],
[
"scientist",
"empirical investigator"
],
[
"roboticist",
"aficionado of autonomous mechatronics"
],
[
"RD",
"principal investigator of research endeavors"
],
[
"secoff",
"sentient firewall entity"
],
[
"cargo",
"the logistics and procurement department"
],
[
"kitchen",
"gastronomical laboratory"
],
[
"bridge",
"command nexus"
],
[
"station",
"orbital habitation module"
],
[
"med",
"the anatomical pathology division"
],
[
"booze",
"ethanolic solution"
],
[
"drunk",
"exhibiting inebriation"
],
[
"cleaning",
"executing sanitation protocols"
],
[
"salvage",
"operational detritus reclamation"
],
[
"am a nerd",
"am an individual with proclivities skewed towards the perspicacious analysis and articulation of technically intricate or esoterically arcane subject matter"
],
[
"geek",
"maven of the digital arts"
],
[
"ratking",
"kingly rodent belonging to the genus Rattus"
],
[
"mouse",
"muridae mammalian entity"
],
[
"monkey",
"simian primate entity"
],
[
"goat",
"caprine quadruped"
],
[
"slime",
"amorphous gelatinous entity"
],
[
"snake",
"serpentine entity"
],
[
"clown",
"harlequin"
],
[
"mime",
"pantomime artificer"
],
[
"dragon",
"scaled, fire-breathing draconian entity"
],
[
"computer",
"computational device"
],
[
"ninja",
"practitioner of ninjutsu"
],
[
"nukie",
"enemy operative"
],
[
"traitor",
"adversary"
],
[
"enemy",
"adversary"
],
[
"dnd",
"dungeons and dragons"
],
[
"jail",
"correctional confinement facility"
],
[
"well,",
"well actually,"
],
[
"robot",
"cybernetic organism"
],
[
"alcohol",
"ethanolic solution"
],
[
"actually",
"erm actually"
],
[
"spider",
"arachnid"
],
[
"singu",
"radioactive space-time singularity event"
],
[
"tesla",
"localized high-voltage phenomenon"
],
[
"ame",
"antimatter annihilation engine"
],
[
"solars",
"photovoltaic effect devices"
],
[
"engineer",
"habitation module maintenance technician"
],
[
"detective",
"forensic investigator"
],
[
"chef",
"nutrition expert"
],
[
"botanist",
"vegetation genomics expert"
],
[
"lathe",
"autonomous fabrication module"
],
[
"reporter",
"civilian investigation operative"
],
[
"bartender",
"custodian of ethanolic beverages"
],
[
"janitor",
"sanitation protocol executive"
],
[
"psychologist",
"specialist for socio-neurological connections"
],
[
"qm",
"chief logistical coordinator"
]
],
"prefixes": [],
"suffixes": []
},
{
"id": "polite",
"label": "Polite",
"fork": "Starlight",
"sample": "If you would be so kind.",
"words": [
[
"ggez",
"I love you all and wish you the best!"
],
[
"flukies",
"challenging threat"
],
[
"skill issue",
"good try"
],
[
"asshole",
"friend"
],
[
"damn",
"dang"
],
[
"god",
"gosh"
],
[
"crap",
"shoot"
],
[
"hell",
"heck"
],
[
"ass",
"butt"
],
[
"damnit",
"dang it"
],
[
"dammit",
"dang it"
],
[
"crap",
"poop"
],
[
"dumbass",
"addled"
],
[
"goddamn",
"gosh darn"
],
[
"goddammit",
"gosh darn it"
],
[
"horseshit",
"horse manure"
],
[
"jackass",
"lovely person"
],
[
"Jesus Christ",
"lord above"
],
[
"prick",
"porcupine"
],
[
"pussy",
"coward"
],
[
"an asshole",
"a friend"
]
],
"prefixes": [],
"suffixes": []
},
{
"id": "southern",
"label": "Southern",
"fork": "Starlight",
"sample": "Y'all have a good one.",
"words": [
[
"you all",
"y'all"
],
[
"you guys",
"y'all"
],
[
"isn't",
"ain't"
],
[
"is not",
"ain't"
],
[
"aren't",
"ain't"
],
[
"are not",
"ain't"
]
],
"prefixes": [],
"suffixes": []
},
{
"id": "chav",
"label": "Chav",
"fork": "Starlight",
"sample": "Innit bruv.",
"words": [
[
"believe",
"Adam and Eve"
],
[
"neck",
"Gregory"
],
[
"necks",
"Gregories"
],
[
"fart",
"raspberry"
],
[
"hat",
"titfer"
],
[
"wife",
"trouble"
],
[
"sweetheart",
"treacle"
],
[
"dear",
"treacle"
],
[
"honey",
"treacle"
],
[
"stairs",
"apples and pears"
],
[
"pizza",
"Mona Lisa"
],
[
"balls",
"cobblers"
],
[
"bruh",
"bruv"
],
[
"bro",
"bruv"
],
[
"brother",
"bruvva"
],
[
"friends",
"mates"
],
[
"sister",
"sista"
],
[
"sir",
"guv"
],
[
"security",
"po-po"
],
[
"officer",
"guv"
],
[
"psychologist",
"pill pusher"
],
[
"surgeon",
"sawbones"
],
[
"medbay",
"A and E"
],
[
"credit",
"quid"
],
[
"credits",
"quid"
],
[
"crazy",
"daft"
],
[
"drunk",
"plastered"
],
[
"questionable",
"dodgy"
],
[
"beer",
"bevvy"
],
[
"beers",
"bevvies"
],
[
"excited",
"chuffed"
],
[
"great",
"cracking"
],
[
"very",
"propa"
],
[
"steal",
"nick"
],
[
"stole",
"nicked"
],
[
"stolen",
"nicked"
],
[
"this",
"dis"
],
[
"that",
"dat"
],
[
"these",
"deez"
],
[
"those",
"doze"
],
[
"though",
"al'o"
],
[
"they",
"dey"
],
[
"the",
"da"
],
[
"there",
"dere"
],
[
"them",
"em"
],
[
"than",
"dan"
],
[
"then",
"den"
],
[
"what",
"wot"
],
[
"mom",
"mum"
],
[
"mother",
"mum"
],
[
"little",
"lil"
],
[
"hi",
"oi"
],
[
"hey",
"oi"
],
[
"hello",
"oi"
],
[
"cigarette",
"ciggy"
],
[
"cigarettes",
"ciggies"
],
[
"asshole",
"berk"
],
[
"idiot",
"twit"
],
[
"guy",
"bloke"
],
[
"man",
"bloke"
],
[
"guys",
"blokes"
],
[
"scientist",
"boffin"
],
[
"buddy",
"mate"
],
[
"pal",
"mate"
],
[
"lady",
"dame"
],
[
"woman",
"dame"
],
[
"girl",
"bird"
],
[
"girls",
"birds"
],
[
"borg",
"tin can"
],
[
"borgs",
"tin cans"
],
[
"right",
"roight"
],
[
"fine",
"foine"
],
[
"good",
"roight propa"
],
[
"nice",
"noice"
],
[
"cool",
"cor"
],
[
"my",
"me"
],
[
"you",
"yew"
],
[
"your",
"yer"
],
[
"feather",
"feavver"
],
[
"feathers",
"feavvers"
],
[
"feathery",
"feavvery"
],
[
"dwarf",
"manlet"
],
[
"dwarves",
"manlets"
],
[
"lighter",
"loighta"
],
[
"alright",
"awlrite"
],
[
"food",
"chow"
],
[
"something",
"sumfin"
],
[
"nothing",
"nuffin"
]
],
"prefixes": [],
"suffixes": []
},
{
"id": "archaic",
"label": "Archaic",
"fork": "Starlight",
"sample": "Thou art most welcome.",
"words": [
[
"tell",
"advise"
],
[
"so far",
"as of this date"
],
[
"let me know",
"awaiting your reply"
],
[
"get",
"secure"
],
[
"consider",
"deem"
],
[
"my",
"mine"
],
[
"you",
"thou"
],
[
"your",
"thy"
],
[
"yours",
"thine"
],
[
"yourself",
"thyself"
],
[
"shall",
"shalt"
],
[
"has",
"hast"
],
[
"have",
"hath"
],
[
"are",
"art"
],
[
"does",
"doth"
],
[
"presented",
"bestowed"
],
[
"wonderful",
"wonderous"
],
[
"by chance",
"perchance"
],
[
"this",
"thee"
],
[
"yes",
"aye"
],
[
"beg",
"beseech"
],
[
"gloom",
"drear"
],
[
"full",
"fraught"
],
[
"rush",
"make haste"
],
[
"careless",
"heedless"
],
[
"from this point onwards",
"hereinafter"
],
[
"of this",
"hereof"
],
[
"under this",
"hereunder"
],
[
"of that",
"thereof"
],
[
"by what",
"whereby"
],
[
"by which",
"whereby"
],
[
"under that",
"thereunder"
],
[
"in what",
"wherein"
],
[
"after that",
"thereafter"
],
[
"security",
"guard"
],
[
"sec",
"guard"
],
[
"seccie",
"guard"
],
[
"seccies",
"guards"
],
[
"gib",
"butcher"
],
[
"begs",
"pleads"
],
[
"fancy",
"furbished"
],
[
"onto",
"unto"
],
[
"can i",
"am I allowed to"
],
[
"upon",
"unto"
],
[
"where",
"whither"
],
[
"obligated",
"allegiant"
],
[
"and",
"an"
],
[
"accuse",
"appeach"
],
[
"accused",
"appeached"
],
[
"was",
"have been"
],
[
"stain",
"taint"
],
[
"stained",
"tainted"
],
[
"take place",
"befall"
],
[
"taken place",
"befall'n"
],
[
"happened",
"befall'n"
],
[
"probably",
"belike"
],
[
"most likely",
"belike"
],
[
"madenning",
"bemadding"
],
[
"suggest",
"bespeak"
],
[
"indicate",
"bespeak"
],
[
"immediately",
"betimes"
],
[
"at once",
"betimes"
],
[
"song",
"catch"
],
[
"altar",
"chantry"
],
[
"merchant",
"chapman"
],
[
"salesman",
"chapman"
],
[
"shopkeeper",
"chapman"
],
[
"shopkeeper",
"chapman"
],
[
"cheater",
"cog"
],
[
"cheat",
"cozen"
],
[
"swindler",
"cog"
],
[
"ilk",
"consort"
],
[
"partnership",
"consort"
],
[
"crown",
"coronal"
],
[
"burden",
"fardel"
],
[
"certainly",
"forsooth"
],
[
"indeed",
"forsooth"
],
[
"obese",
"corpulent"
],
[
"occured",
"befall'n"
],
[
"carved",
"carven"
],
[
"coward",
"craven"
],
[
"idiot",
"cur"
],
[
"ruin",
"defile"
],
[
"ruined",
"defiled"
],
[
"pretend",
"feign"
],
[
"forsee",
"forbode"
],
[
"abandoned",
"forlorn"
],
[
"desolate",
"forlorn"
],
[
"abandon",
"forsake"
],
[
"fraught",
"full"
],
[
"old woman",
"gammer"
],
[
"frown",
"glower"
],
[
"chop",
"hew"
],
[
"slice",
"hew"
],
[
"slice",
"hew"
],
[
"evil",
"ill"
],
[
"wrong",
"ill"
],
[
"sharp",
"keen"
],
[
"reluctant",
"loth"
],
[
"corner",
"nook"
],
[
"true",
"sooth"
],
[
"faint",
"swoon"
],
[
"twisted",
"thrawn"
],
[
"misshapen",
"thrawn"
],
[
"stubborn",
"thrawn"
],
[
"obstinate",
"thrawn"
],
[
"travel",
"traverse"
],
[
"thwart",
"foil"
],
[
"thwart",
"stop"
],
[
"refuse",
"shun"
],
[
"pest",
"varmint"
],
[
"ghost",
"wraith"
],
[
"apparition",
"wraith"
],
[
"long ago",
"yore"
],
[
"stupid",
"foolish"
],
[
"yay",
"hurrah"
],
[
"hooray",
"hurrah"
],
[
"old",
"olde"
],
[
"right now",
"forthwith"
],
[
"boss",
"sire"
],
[
"clown",
"jester"
],
[
"fight",
"duel"
],
[
"write",
"inscribe"
],
[
"draw",
"inscribe"
],
[
"one time",
"once"
],
[
"two times",
"twice"
],
[
"three times",
"thrice"
],
[
"security officer",
"guardsman"
],
[
"sec off",
"guardsman"
],
[
"secoff",
"guardsman"
],
[
"bar",
"tavern"
],
[
"passenger",
"peasant"
],
[
"hi",
"greetings"
],
[
"hey",
"greetings"
],
[
"heya",
"greetings"
],
[
"hello",
"salutations"
],
[
"yeah",
"indeed"
],
[
"yep",
"indeed"
],
[
"yup",
"indeed"
],
[
"ok",
"alright"
],
[
"k",
"alright"
],
[
"okay",
"alright"
],
[
"sure",
"alright"
],
[
"below",
"beneath"
],
[
"the",
"yon"
],
[
"need",
"require"
],
[
"maybe",
"perhaps"
],
[
"is",
"'s"
],
[
"alcohol",
"booze"
],
[
"liquor",
"booze"
],
[
"id",
"identification"
],
[
"crate",
"chest"
],
[
"locker",
"closet"
],
[
"do",
"doth"
],
[
"beg",
"plead"
],
[
"saw",
"observed"
],
[
"food",
"grub"
],
[
"delicious",
"exquisite"
],
[
"cool",
"enjoyable"
],
[
"think",
"believe"
],
[
"indeed",
"certainly"
],
[
"now",
"immediately"
],
[
"or",
"else"
],
[
"will",
"shall"
],
[
"i am thirsty",
"I require a drink"
],
[
"hate",
"loathe"
],
[
"old",
"olden"
],
[
"bike horn",
"honker"
],
[
"flashlight",
"torch"
],
[
"pen",
"quill"
],
[
"lobby",
"anteroom"
],
[
"syndicate",
"traitor"
],
[
"syndi",
"traitor"
],
[
"good",
"well"
],
[
"fate",
"doom"
],
[
"space",
"void"
],
[
"i'm",
"I am"
],
[
"I'm",
"I am"
],
[
"chef",
"cook"
],
[
"captain",
"lord"
],
[
"chaplain",
"vicar"
],
[
"chapel",
"basilica"
],
[
"ask",
"request"
],
[
"ask for",
"request"
],
[
"move",
"relocate"
],
[
"will",
"shalt"
],
[
"bad",
"unpleasant"
],
[
"got rid of",
"removed"
],
[
"guy",
"man"
],
[
"guys",
"people"
],
[
"airlock",
"door"
],
[
"sorry",
"I apologise"
],
[
"hey",
"pardon me"
],
[
"chair",
"seating"
],
[
"can",
"may"
],
[
"kill",
"murder"
],
[
"guess",
"surmise"
],
[
"wow",
"astonishing"
],
[
"why",
"for what reason"
],
[
"im",
"I am"
],
[
"sink",
"taps"
],
[
"beaker",
"vial"
],
[
"toolbox",
"case"
],
[
"rubber stamp",
"wax stamp"
],
[
"tiles",
"flooring"
],
[
"maintenance",
"alleyways"
],
[
"going on",
"happening"
],
[
"tasty",
"delectable"
],
[
"myself",
"mineself"
],
[
"i am hungry",
"I require grub"
],
[
"you suck",
"thou are foul"
],
[
"please",
"I request of thee"
],
[
"secway",
"patrol cart"
],
[
"janicart",
"cart"
],
[
"soda",
"drink"
],
[
"pop",
"drink"
],
[
"wants",
"wishes"
],
[
"want",
"wish for"
],
[
"use",
"utilize"
]
],
"prefixes": [],
"suffixes": []
}
]
};
